### ISSUE TITLE
Create dynamic URLs to allow for easy sharing

### ISSUE THREAD

**Issue by Ycreak** [briannededeugd/BrassiToL#1]
AS a product owner
I WANT the application to dynamically update its URL when using it 
SO THAT we can easily share views/filters/selections with colleagues

To quote the suggestions document:
> A thing that I like to have in webapps, is a dynamic link, that reflects exactly what is on the screen so that you can share your result to others.

**Comment by briannededeugd** [comment]
Dit is een grote dus bij deze houd ik bij waar ik mee bezig ben:
- [ ]  Verzamel de waarde van een checkbox **als** deze gecheckt is
- [ ] Koppel de waarde aan de relevante filtercategorie (in een array, zodat er meerdere filters geaccepteerd worden)
- [ ] Verstuur deze waardes naar een dynamische store die de url updatet
- [ ] Zorg dat de url-parameters uitgelezen wordt als de boom wordt ingeladen
       - Geen parameters = geen filters = standaard view
- [ ] Als filters uit worden gezet, wordt de url ook geüpdatet
       - Geen filters = geen parameters = standaard view

**Comment by Ycreak** [comment]
Zulke lijstjes kun je beter in een draft Pull Request zetten, dan kunnen we ook per commit de voortgang zien en vergelijken :D

**Comment by briannededeugd** [comment]
> Zulke lijstjes kun je beter in een draft Pull Request zetten, dan kunnen we ook per commit de voortgang zien en vergelijken :D

Oh top, heb ik gedaan!

**Comment by KPHendriks** [comment]
This works great Brianne! Congrats!
