### ISSUE TITLE
Geography filter > Regions is now wrong

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#11]
When trying to select a Region, the filter now shows some countries instead.
This was correct at first but changed when the map was updated to include all the regions, including US states and Russian territories, etc. Maybe this helps solve the problem?

**Comment by KPHendriks** [comment]
Hoi Brianne.
Ik denk dat dit ook wel een eenvoudige is om mee te nemen?
Zou netjes zien dit te fixen. :-)

**Comment by KPHendriks** [comment]
Hier had ik over gemaild. Als dit lukt dan dit issue ook afgevinkt. :-)

**Comment by briannededeugd** [comment]
Dit is gelukt, dus ik sluit de issue!

**Comment by KPHendriks** [comment]
Great!!
