### ISSUE TITLE
Allow filters to be unionized and intersected

### ISSUE THREAD

**Issue by Ycreak** [briannededeugd/BrassiToL#2]
AS a product owner
I WANT to be able to intersect and unionize filters filters
SO THAT we can easily combine filters

To quote the suggestions document:
> if relevant, have an option to combine filters with AND instead of OR. for instance between the four characteristics.

> Misschien het meest fundamenteel: de gebruiker de keuze geven om de filters als ‘union’ (inclusief) of ‘intersection’ (exclusief) te gebruiken (uitleg: Union of the sets A and B , denoted A ∪ B , is the set of all objects that are a member of A , or B , or both. The union of {1, 2, 3} and {2, 3, 4} is the set {1, 2, 3, 4} . Intersection of the sets A and B , denoted A ∩ B , is the set of all objects that are members of both A and B).

**Comment by Ycreak** [comment]
Schatting: 2 dagen.

**Comment by KPHendriks** [comment]
Hoi Brianne. Als de dynamic URLs te lang duurt, is dit issue een goede om aan te werken.
Minstens zo belangrijk, lijkt me. :-)
(En mm makkelijker?)

**Comment by Ycreak** [comment]
Belangrijk is dat deze switch ook via de url wordt meegegeven en geinterpreteerd kan worden (:
