### ISSUE TITLE
Colour tribe Aethionema

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#20]
Zou mooi zijn de tribus Aethionema (soorten die niet aan een supertribe toegekend zijn) toch een kleur te geven (grijs?), om een onderscheid te maken met de outgroups; een andere optie is dat Aethionema wel wit blijft, maar de lijnen van de outgroups wellicht gestreept worden, om zo duidelijk te maken dat zij geen onderdeel uitmaken van de familie Brassicaceae.

**Comment by briannededeugd** [comment]
@Ycreak 

Ik weet niet zeker of dit helemaal mogelijk is.

De kleuren worden toegeschreven op basis van de Supertribe van de relevante plant. Van alle voorkomende Supertribes uit de database heb ik een colorScale gemaakt. Omdat Aethionema een andere subfamilie is en de soorten van deze familie in de data geen Supertribe hebben, wordt deze familie automatisch ingedeeld bij NA. De outgroups bevatten ook geen Brassicaceae soorten omdat dit ook al helemaal andere families zijn, waardoor hier dezelfde logica op wordt toegepast en ze dus ook bij NA worden ingedeeld, met als resultaat dat de Aethionema en de outgroups dezelfde kleur krijgen.

Ik heb wel gekeken naar deze logica en een paar dingen geprobeerd, maar denk dat dit een aantal dagen zal duren om om te gooien mochten we willen dat dit anders werkt.

**Comment by Ycreak** [comment]
Oké! Dan is dit ticket binnen de huidige implementatie niet mogelijk en kan deze niet opgepakt worden binnen de sprint. Om dit dan toch netjes op te lossen, moet een nieuwe/betere implementatie worden bedacht en geimplementeerd worden. Dit ticket kan dan van het project af en zal opnieuw moeten worden ingeschat (wordt waarschijnlijk een 13-punter of meer). Geen probleem, pakken we die later nog een keertje op!
