### ISSUE TITLE
Correct fonts for species names and author names

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#22]
De soortnaam kan beste geschreven worden met kleine letters en alleen een hoofdletter voor de genusnaam, omdat dat wetenschappelijk accuraat is. Dit geldt voor de tip labels en de popup.

Ook zouden we de auteur van iedere soort moeten toevoegen in de popup, maar die gegevens zou ik dan eerst nog moeten toevoegen aan de metadatafile (niet veel werk denk ik). Voorbeeld van hoe de volledige soortnaam dan in de popup moet verschijnen: _Arabidopsis thaliana_ (L.) Heynh.

**Comment by briannededeugd** [comment]
(Vereist nieuwe metadata).

**Comment by KPHendriks** [comment]
Hoi Brianne.

Ik bedenk ik me dat auteursnamen vaak vrij exotische characters bevatten. Zou mooi zijn een lettertype te kiezen wat de meeste niet westerse lettertypen ook bevat. Test maar eens met een naam als Barış Özüdoğru, één van onze core collaborators.

Succes!

**Comment by briannededeugd** [comment]
Oh, goed dat je het zegt! Ik zal hem toevoegen en kijken of het huidige lettertype deze tekens meeneemt.

**Comment by briannededeugd** [comment]
<img width="401" alt="Screenshot 2024-08-13 at 13 51 44" src="https://github.com/user-attachments/assets/ca2a6f33-293c-4ebc-bf79-67b2c7095b35">

Hij lijkt alle tekens te herkennen! Dit is hoe Barış Özüdoğru erin komt te staan.

**Comment by briannededeugd** [comment]
@KPHendriks 

Vind je dit lettertype geschikt voor de soortnaam? Op deze manier zijn de verschillen tussen hoofdletters en kleine letters (een stuk beter) te zien. Het is hetzelfde lettertype als de bodytekst.

<img width="900" alt="Screenshot 2024-08-13 at 14 45 39" src="https://github.com/user-attachments/assets/d101301f-7d90-4a86-a6fd-0fd80c6cf37c">
<img width="900" alt="Screenshot 2024-08-13 at 14 46 04" src="https://github.com/user-attachments/assets/32fa8784-3e0a-4028-b306-7a2bd33d2cbc">

**Comment by KPHendriks** [comment]
Lijkt me goed ja! Snap dat het oorspronkelijke ontwerp dan wat aangedaan wordt...maar is toch wel belangrijk om die namens goed te spellen.

Kan t moeilijk beoordelen vanaf mobiel, maar mm kleiner font om beter hele soortnaam op één regel te krijgen?

Thanks!!

**Comment by briannededeugd** [comment]
> kleiner font om beter hele soortnaam op één regel te krijgen?

Dit kan, maar omdat sommige titels een stuk langer zijn dan anderen moet het dan wel erg klein worden om te verzekeren dat ongeacht de lengte, alle titels op één regel passen.

**Comment by KPHendriks** [comment]
Nee dat hoeft niet hoor, niet alles. Maar wel mooi als omgekeerd niet álle
soortnamen over meerdere regels verdeeld worden. ;-)

Op di 13 aug. 2024 16:37 schreef Brianne de Deugd ***@***.***

**Comment by briannededeugd** [comment]
@KPHendriks 

Ah snap ik, dat is gelukkig zeker niet het geval op de desktop! Ik denk dat het komt door het formaat van een mobiele telefoon die alles een stuk kleiner maakt, maar op een computer passen bijna alle namen op één regel :). Zo ziet dat er dan uit:

https://github.com/user-attachments/assets/77cb69a6-89aa-4bad-8203-26c19547c7a7

**Comment by KPHendriks** [comment]
Ah super. Ja zou kunnen dat dat t was. :-)
Thanks!!

**Comment by KPHendriks** [comment]
Officieel hoort trouwens de auteursnamen direct achter de soortnaam en dus
niet standaard op een nieuwe regel. Is dat makkelijk aan te passen, of
lastig door de andere font? In laatste geval zou ik t voor nu maar laten.
Anders mag t aangepast. Als y dan toch soms of vaak of twee regels uitkomt,
geen probleem.

Op wo 14 aug. 2024 08:59 schreef Brianne de Deugd ***@***.***

**Comment by briannededeugd** [comment]
Ik heb het aangepast! In de kleine popup staan ze er meestal wel onder omdat die niet zoveel ruimte heeft, maar in de grote staan ze er nu standaard naast tenzij het niet past.

**Comment by KPHendriks** [comment]
Super!

Op wo 14 aug. 2024 10:11 schreef Brianne de Deugd ***@***.***

**Comment by KPHendriks** [comment]
@briannededeugd 

Ik zie nu ook dat in de kleine popup (bij hoveren, niet clicken) de auteur altijd onder de soortnaam staat. Kan deze, net als in de grote popup, ook achter de soortnaam (als dat past)? Is netter, zeker omdat de auteur vaak slechts "L." is (voor Linnaeus).

**Comment by KPHendriks** [comment]
Ah ik zie nu dat je dit al wel geschreven had hierboven. Toch denk ik dat een auteur als "L." beter achter en niet onder de soortnaam kan, als dat nog gemakkelijk aan te passen is. :-)
