### ISSUE TITLE
Distinction between "species details" and "specimen details"

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#25]
_Eigenlijk_ zouden we een onderscheid moeten maken tussen “species details” en “specimen details” in de popup.

Iedere "species" (soort) wordt in de BrassiToL vertegenwoordigd door één (maar soms ook wel twee, en in volgende versies van de BrassiTol soms wel vijf of nog meer) "specimens" (dus meerdere fysieke planten die ooit verzameld zijn en nu in het lab het DNA van gesequenced); iemand kan zeggen dat een specimen verkeerd geïdentificeerd is en het specimen willen bekijken in de echte collectie, het herbarium; en daarom moeten die "specimen details" eigenlijk getoond! 

Specimen details zouden zijn: land, datum en persoon van verzamelen, de collectie waar het gedroogde exemplaar nu opgeslagen ligt en het nummer dat het specimen in die collectie heeft. Ik heb zulke gegevens uiteraard, maar had die nog niet opgenomen in de metadata tabel. Het is namelijk best wat werk dat te doen (voor mij, Kasper)!

Ik stel voor dat we het ontwerp van de app nu aanpassen om dit wél al in te voegen. Ik zal dan voor een eerste set specimens (10 ofzo) deze gegevens toevoegen aan de metadata file. Die krijgt dus extra kolommen. Ik kan dan na de zomer voor alle specimens deze gegevens gaan opsnorren en toevoegen. Voor de specimens waar we de data nu dan niet voor hebben, laten we de velden gewoon even leeg.

Overigens zouden we dan ook (makkelijk?) een kopje "Specimens" kunnen toevoegen aan de filters. Daarbinnen dan een paar logische opties om te filteren, zoals "Collection" (dat is dan dus het herbarium of het museum), "Collector" (de persoon die verzamelde), "Year collected", "Country collected".

Ik stel voor dat we de popup "omkeerbaar" maken, net als nu voor de BrassiToL en de wereldkaar. De ene kant (default) toont dan de "species details", de andere zijde de "specimen details".

Tenslotte, zie ook #37 .

**Comment by KPHendriks** [comment]
@briannededeugd 

Mijn oog valt er nu plots op dat in de popup een DNA helix icoontje wordt getoond voor de taxonomische "ketting". Dat icoontje zou ik eerder gebruiken voor de link naar de ruwe data; zie mijn mailtje over specimen details.

Vóór die "ketting" zou ik eerder een soort super simpel ToL icoontje plaatsen, of helemaal geen icoon.

**Comment by KPHendriks** [comment]
@briannededeugd 

Hoi Brianne.
Áls je er nog één uurtje in wilt stoppen, een keer, anders niet hoor. ;-)

-In de metadata CSV zijn de namen van auteurs nu correct. 
Had een paar andere ook nog geupdate (in de laatste file die ik je stuurde). 
Als er tóch gekke tekens blijven komen in de app, ligt het denk ik niet aan de metadata csv file.
-In de volgende kolommen moest ik ook wat namen van mensen aanpassen ivm die tekens, die zouden dus eigenlijk ook nog even opnieuw gemaakt moeten worden:  
COLLECTOR
COLLECTOR_CODE
IDENTIFIER
BIOMATERIAL_PROVIDER
-Tenslotte, ik zie dat bij de specimen details nog mist: "Collection country"; de data daarvoor staan in de kolom "COLLECTION_COUNTRY"
Past dat er nog bij?

**Comment by briannededeugd** [comment]
@KPHendriks 

Geen probleem, ik zal ze nog verwerken. De Collection country past er denk ik wel nog bij, en mocht je toch vinden dat het netter kan / dat iets bijvoorbeeld ergens naast moet in plaats van eronder om ruimte te besparen, kan je dat vooral laten weten! We zouden er bijvoorbeeld een lijstje van kunnen maken in plaats van dezelfde opmaak als de species information (dit is zo gedaan).

Waar precies heb je het nieuwe bestand toegestuurd? Als het kan, graag eentje in .txt-format en eentje in .csv-format, dan kan ik testen waar het (misschien) aan ligt. :)

**Comment by KPHendriks** [comment]
Is al gelukt zag ik?
Super!!! 
Lijkt nu helemaal correct, dus die csv file was zeker de oplossing?

Dank!!

**Comment by briannededeugd** [comment]
@KPHendriks 

Ja, het lag dus wel zeker aan het .txt-bestand! Ik denk dat die bepaalde tekens niet 'aankan'.
