### ISSUE TITLE
Always have popup on the screen

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#28]
Zou mooi zijn als de popup altijd geheel in beeld verschijnt. Dus als je een soort onderaan in het scherm aanklikt, wil je eigenlijk dat de popup nog wel binnen je scherm helemaal zichtbaar is, zodat je niet hoeft te scrollen (nu komt zo'n "lage popup" trouwens ook niet in beeld no scrollen, maar staat vast op de oorspronkelijke plek, buiten beeld).

**Comment by Ycreak** [comment]
Bij klik, pop up in midden. Anders altijd popup in beeld.

**Comment by KPHendriks** [comment]
Fijn dat dit werkt, superhandig zo!
