### ISSUE TITLE
Remove duplicate species names from popup in map view

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#32]
Als een soort meer dan eens in de BrassiToL voorkomt, en dus ook in de metadatafile, verschijnt deze nu als meer dan één soort op de kaart; daar moet dus eerst een soort functie overheen om alleen de unieke waarden te tonen.

**Comment by KPHendriks** [comment]
Als voorbeeld, kies "Draba funckii".

**Comment by Ycreak** [comment]
Schatting: 1 dag.
