### ISSUE TITLE
Update color scale in map view

### ISSUE THREAD

**Issue by KPHendriks** [briannededeugd/BrassiToL#36]
De kleurenschaal gaat nu van wit naar groen; wanneer er dan maar één soort aanwezig is, is dat nauwelijks zichtbaar. Misschien dus beter om kleurenschaal van de ene naar de andere kleur te doen? Van oranje naar groen bijvoorbeeld. Eventueel kan er nog een middenkleur zijn ook, om onderscheid tussen de landen extra te vergroten (en wit als midden is gewoon niet duidelijk, want landen zonder de soorten zijn ook wit).

**Comment by Ycreak** [comment]
Landen waar niets zit, worden zwart. Wit is 1 soort. Schaal mag 1 tot 10 zijn. 
Schatting: 1 dag.
