### ISSUE TITLE
AND/OR button not readable

### ISSUE THREAD

**Issue by Ycreak** [briannededeugd/BrassiToL#67]
I noticed the and/or button for the filter is not readable on my machine.

![screenshot-2024-08-05_10:57:53](https://github.com/user-attachments/assets/2e845859-fd2d-44d3-a2b6-85fa7aa6408f)

Probably some CSS that is being difficult (:

**Comment by briannededeugd** [comment]
Whoops, I'll fix this asap! 

Also, I temporarily lifted the ruleset for the main branch that requires a review before merging, as I gathered you and Kasper are both away on vacation these next two weeks. Is that okay or would it be better to put the rule back in place?

**Comment by Ycreak** [comment]
Interesting: it is only unreadable on Firefox :O Works on my other browsers. But my Firefox is the ESR version, so it is a bit older (v115). If it works on your firefox, then there is no problem! Solved!
